BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;
using BestRestaurants.Models;

namespace BestRestaurants.Models
{
    public class BestRestaurantsContext : DbContext
    {
        public virtual DbSet<Cuisine> Cuisine { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }

        public virtual DbSet<Review> Reviews {get;set;}

        public BestRestaurantsContext(DbContextOptions options) : base(options)
        {
            
        }
    }
}

BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
    public class Cuisine
    {
        public string Name { get; set; }
        public string Description { get; set; } 
        public string Country { get; set; }
        public string ImgURL { get; set; }
        public int Count {get;set;}
        public int Id { get; set; }
    }
}

BestRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
    public class Restaurant
    {
        public int RestaurantId {get;set;}        
        public string Name { get; set; }
        public string Description { get; set; }
        public Address Address { get; set; }
        public string PriceRange { get; set; }
        public int CuisineId {get;set;}
    }

    public class Address
    {
        public string Street { get; set ;}
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }
}

BestRestaurants/Models/Review.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
    public class Review
    {
        public int Id {get;set;}
        public string UserName { get; set; }
        public int Rating { get; set; }
        public string Body { get; set; }    
        public int RestaurantId {get;set;}
    }
}

BestRestaurants/Controllers/CuisineController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
    public class CuisineController : Controller
    {
        private readonly BestRestaurantsContext _db;

        public CuisineController(BestRestaurantsContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Cuisine> model = _db.Cuisine.ToList();
            return View(model);
        }

        [HttpGet("cuisine/{Id}")]
        public ActionResult CuisineType(int id)
        {
            Cuisine cuisineModel = _db.Cuisine.FirstOrDefault(cuisine => cuisine.Id == id);
            List<Restaurant> restaurantModel = _db.Restaurants.Where(r => r.CuisineId == id).ToList();
            List<double> ratingModel = new List<double>();
            foreach(Restaurant r in restaurantModel)
            {
                double avg = _db.Reviews.Where(x => x.RestaurantId == r.RestaurantId).Average(y => y.Rating);
                ratingModel.Add(avg);
            }
            ViewBag.cuisine = cuisineModel;
            ViewBag.restaurants = restaurantModel;
            ViewBag.rating = ratingModel;
            return View();
        }

        [HttpGet("cuisine/{cuisineId}/restaurant/{Id}")]

        public ActionResult Restaurant(int cuisineId, int Id)
        {
            Restaurant restaurantModel = _db.Restaurants.FirstOrDefault(r => r.RestaurantId == Id) as Restaurant;
            List<Review> reviewModel = _db.Reviews.Where(rv => rv.RestaurantId == Id).ToList();
            double ratingModel = _db.Reviews.Where(rv => rv.RestaurantId == Id).Average(y => y.Rating);
            ViewBag.restaurant = restaurantModel;
            ViewBag.reviews = reviewModel;
            ViewBag.rating = ratingModel;
            ViewBag.cuisineId = cuisineId;
            return View();
        }

        // public ActionResult Create(int cuisineId, int Id)
        // {
        //     ViewBag.cuisineId = cuisineId;
        //     ViewBag.Id = Id;
        //     return View();
        // }
        [HttpGet("cuisine/create/")]
        public ActionResult Create(int cuisineId, int Id)
        {
            ViewBag.cuisineId = cuisineId;
            ViewBag.Id = Id;
            return View();
        }

        [HttpPost("cuisine/create/")]
        public ActionResult Create(Review review, int cuisineId)
        {
            _db.Reviews.Add(review);
            _db.SaveChanges();
            return Redirect("cuisine/{cuisineId}/restaurant/{review.Id}");
        }
    }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

BestRestaurants/Controllers/RestaurantController.cs
// using Microsoft.AspNetCore.Mvc;
// using BestRestaurants.Models;
// using System.Collections.Generic;
// using System.Linq;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.AspNetCore.Mvc.Rendering;

// namespace BestRestaurants.Controllers
// {
//     public class RestaurantController : Controllers
//     {
        
//     }
// }

BestRestaurants/Views/Cuisine/Create.cshtml
@model BestRestaurants.Models.Review;
@using BestRestaurants.Models;


<h4>Add a Review</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.UserName)
    @Html.TextBoxFor(model => model.UserName)

    @Html.LabelFor(model => model.Rating)
    @Html.TextBoxFor(model => model.Rating)

    @Html.LabelFor(model => model.Body)
    @Html.TextBoxFor(model => model.Body)

   <input type="hidden" name="RestaurantId" value=@($"{ViewBag.Id}")>
  

    <button type="submit" value="Add Review" class="btn btn-default">Save Review</button>
}
 <input type="hidden" name="cuisineId" value=@($"{ViewBag.cuisineId}")>

BestRestaurants/Views/Cuisine/CuisineType.cshtml
@using BestRestaurants.Models;

@using System.Collections.Generic;

@{
    Layout = "_Layout";
    var r = ViewBag.restaurants as List<Restaurant>;
}

<h1>@($"{ViewBag.cuisine.Name}")</h1>
<h3>@($"{ViewBag.cuisine.Country}")</h3>
<p>@($"{ViewBag.cuisine.Description}")</p>


    @for (var i =0; i<r.Count; i++)
    {
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                 <input type="hidden" name="Id" value=@($"{r[i].RestaurantId}")>
                 <input type="hidden" name="cuisineId" value=@($"{ViewBag.cuisine.Id}")>
                <a href="@($"/cuisine/{ViewBag.cuisine.Id}/restaurant/{r[i].RestaurantId}")"><h5 class="card-title">@($"{r[i].Name}")</h5></a>
                <h6 class="card-subtitle mb-2 text-muted">@($"{ViewBag.rating[i]}")</h6>
                <p class="card-text">@($"{r[i].Description}")</p>
            </div>
        </div>
    }

BestRestaurants/Views/Cuisine/Index.cshtml
@{
    Layout = "_Layout";
}
@using BestRestaurants.Models;

<h1>Cuisine</h1> 

@{ 
    foreach (Cuisine cuisine in Model)
    {
            <div class="card bg-dark text-white col-md-4 col-sm-6">
            <a href='@($"cuisine/{cuisine.Id}")' id='@($"{cuisine.Id}")'>
            <img src=@Url.Content($"{cuisine.ImgURL}") class="card-img" alt=$"{cuisine.Name}">
            <div class="card-img-overlay">
                <h5 class="card-title">@($"{cuisine.Name}")</h5>
                <p class="card-text">@($"{cuisine.Description}")</p>
                <p class="card-text">@(cuisine.Count==1 ? $"There are {cuisine.Count} restaurant in your area!" : $"There are {cuisine.Count} restaurants in your area!")</p>
            </div>
            </a>
        </div>
    }
}

BestRestaurants/Views/Cuisine/Restaurant.cshtml
@using BestRestaurants.Models;

@{
    Layout = "_Layout";
}



<h1>@($"{ViewBag.restaurant.Name}")</h1>

<h5>@($"{ViewBag.restaurant.PriceRange} | {ViewBag.rating}")</h5>

<h5>@($"{ViewBag.restaurant.Address}")</h5>

<p>@($"{ViewBag.restaurant.Description}")</p>

@{ 
    foreach (Review rv in ViewBag.reviews)
    {
        <div class="card bg-dark text-white">
            <h5 class="card-title">@($"User Name: {rv.UserName} | Rating: {rv.Rating}")</h5>
            <p class="card-text">@($"{rv.Body}")</p>
        </div>
    }
}
<input type="hidden" name="cuisineId" value=@($"{ViewBag.cuisineId}")>
<input type="hidden" name="Id" value=@($"{ViewBag.restaurant.RestaurantId}")>
<button class="btn btn-outline-dark">@Html.ActionLink("Add a Review", "Create", "Cuisine", new {cuisineId = ViewBag.cuisineId, Id = ViewBag.restaurant.RestaurantId})</button>

BestRestaurants/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<h1>Best Restaurants</h1>

<button class="btn btn-outline-dark">@Html.ActionLink("Search by Cuisine", "Index", "Cuisine")</button>

BestRestaurants/Views/Shared/Footer.cshtml
<footer class="footer mt-auto py-3">
    <p> Yo. I'm a footer.</p>
</footer>

BestRestaurants/Views/Shared/Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>The Best Restaurants</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @Html.Partial("Header")
    @RenderBody()
    @Html.Partial("Footer") 
  </body>
</html>